### PR TITLE
Feat: move tests next to code

### LINKED ISSUE #467: feat: Move tests next to code
Simplify core test file structure by moving tests in `/src` next to code.

`/packages/core/tests/createOffer.test.ts` > `/packages/core/src/actions/order/createOffer.test.ts`

### PR DESCRIPTION
**Pull request by sanieni6**
## Description
Simplify core test file structure by moving tests in /src next to code.
## What type of PR is this? (check all applicable)

- [ ✅ ] 🧑‍💻 Code Refactor (`refactor:`)

## Added tests?

- [✅  ] 👍 tested!

## Added to documentation?

- [✅  ] 🙅 no documentation needed

## Closing Issues
closes #467

### CODE REVIEW

**Comment by sanieni6** [comment]
Hi @gershon i just created a new PR, please kindly review 🙏

**Comment by gershon** [comment]
Looks good! But there are some typecheck errors on `packages/core/src/createConfig.test.ts`, you can run `pnpm typecheck` in `packages/core` to view errors. I'll merge when this is fixed.

**Comment by sanieni6** [comment]
Thanks for the feedback, @gershon I’ve fixed the issue by replacing the `test` function with the `it` function from Vitest, as that aligns with the testing framework you're using for the other tests.

**Comment by sanieni6** [comment]
hey @gershon let me know if you need something else ☺️

**Comment by gershon** [comment]
Hi @sanieni6, everything looks good as is. I'll do some final checks and merge it soon. 🚀

**Comment by gershon** [comment]
Hi @sanieni6 , thank you for your contribution! Due to some update conflicts on our end, we have decided to take it into account for ODHACK, but we will push and merge your changes in another branch ourselves.

**Pull request closed without merging**
